### PR TITLE
Updates to chapter 1... needs some work.

### PR DESCRIPTION
**Pull request by awilmore**
Yeah... spent a few hours on this update... not totally happy with it but it has potential.

### CODE REVIEW

**Comment by ma78** [comment]
choking
##%@@#$$#@

On Wed, Sep 18, 2013 at 4:59 PM, Adam Wilmore notifications@github.comwrote:

> Yeah... spent a few hours on this update... not totally happy with it but
> 
> ## it has potential.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/awilmore/bookideanapolinash master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/ma78/bookideanapolinash/pull/1
> Commit Summary
> - Updates to chapter 1... needs some work.
> 
> File Changes
> - _M_ Chapter 1https://github.com/ma78/bookideanapolinash/pull/1/files#diff-0(6)
> 
> Patch Links:
> - https://github.com/ma78/bookideanapolinash/pull/1.patch
> - https://github.com/ma78/bookideanapolinash/pull/1.diff

## 

Cheers
Marc

**Comment by ma78** [comment]
now that i'm breathing again

i dont understand why you forked it.. did you need to fork it to edit it?
can't you just edit the master?

got any spare slots this week to explain this shit to me?

On Wed, Sep 18, 2013 at 5:03 PM, Marc Napoli marcadrian78@gmail.com wrote:

> choking
> ##%@@#$$#@
> 
> On Wed, Sep 18, 2013 at 4:59 PM, Adam Wilmore notifications@github.comwrote:
> 
> > Yeah... spent a few hours on this update... not totally happy with it but
> > 
> > ## it has potential.
> > 
> > You can merge this Pull Request by running
> > 
> >   git pull https://github.com/awilmore/bookideanapolinash master
> > 
> > Or view, comment on, or merge it at:
> > 
> >   https://github.com/ma78/bookideanapolinash/pull/1
> > Commit Summary
> > - Updates to chapter 1... needs some work.
> > 
> > File Changes
> > - _M_ Chapter 1https://github.com/ma78/bookideanapolinash/pull/1/files#diff-0(6)
> > 
> > Patch Links:
> > - https://github.com/ma78/bookideanapolinash/pull/1.patch
> > - https://github.com/ma78/bookideanapolinash/pull/1.diff
> 
> ## 
> 
> Cheers
> Marc

## 

Cheers
Marc

**Comment by awilmore** [comment]
There's no way I can touch your code unless you make me a contributor. I
can however fork your shit because it's public "open source" (you have to
pay to make it private).

Lunch tomorrow?

**Comment by ma78** [comment]
right.. and i can't control what yuo do with it now. i see.

if you want tmerge it back into my main tree and get rid of your branch now
that i have added you as a contributor.. you submit a pull request to me? i
accept it, then you delete your branch?

On Wed, Sep 18, 2013 at 5:12 PM, Adam Wilmore notifications@github.comwrote:

> There's no way I can touch your code unless you make me a contributor. I
> can however fork your shit because it's public "open source" (you have to
> pay to make it private).
> 
> Lunch tomorrow?
> 
> On Wednesday, September 18, 2013, ma78 wrote:
> 
> > now that i'm breathing again
> > 
> > i dont understand why you forked it.. did you need to fork it to edit
> > it?
> > can't you just edit the master?
> > 
> > got any spare slots this week to explain this shit to me?
> > 
> > On Wed, Sep 18, 2013 at 5:03 PM, Marc Napoli <marcadrian78@gmail.com<javascript:_e({},
> > 'cvml', 'marcadrian78@gmail.com');>>
> > wrote:
> > 
> > > choking
> > > ##%@@#$$#@
> > > 
> > > On Wed, Sep 18, 2013 at 4:59 PM, Adam Wilmore <
> > > notifications@github.com<javascript:_e({}, 'cvml', '
> > > notifications@github.com');>
> > > wrote:
> > > 
> > > > Yeah... spent a few hours on this update... not totally happy with it
> > > > but
> > > > 
> > > > ## it has potential.
> > > > 
> > > > You can merge this Pull Request by running
> > > > 
> > > > git pull https://github.com/awilmore/bookideanapolinash master
> > > > 
> > > > Or view, comment on, or merge it at:
> > > > 
> > > > https://github.com/ma78/bookideanapolinash/pull/1
> > > > Commit Summary
> > > > - Updates to chapter 1... needs some work.
> > > > 
> > > > File Changes
> > > > - _M_ Chapter 1<
> > > >   https://github.com/ma78/bookideanapolinash/pull/1/files#diff-0>(6)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/ma78/bookideanapolinash/pull/1.patch
> > > > - https://github.com/ma78/bookideanapolinash/pull/1.diff
> > > 
> > > ## 
> > > 
> > > Cheers
> > > Marc
> > 
> > ## 
> > 
> > Cheers
> > Marc
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ma78/bookideanapolinash/pull/1#issuecomment-24644996>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ma78/bookideanapolinash/pull/1#issuecomment-24645145
> .

## 

Cheers
Marc

**Comment by awilmore** [comment]
Pretty much :)

**Pull request closed without merging**
